spring.application.name=sante-kunafoni-app

spring.datasource.url=jdbc:mysql://localhost:3306/santekunafoni?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC

spring.datasource.username=root
<<<<<<< HEAD:src/main/resources/application.properties
<<<<<<< HEAD
spring.datasource.password=2309
=======
spring.datasource.password=1234
>>>>>>> eefc87df9a719d23f26f4a117dcdb406812202bf
=======
spring.datasource.password=6240
>>>>>>> 19be0422d2405370b6be5f5206c9829ff74bc66b:application.properties

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true